-- For Hub
INSERT INTO `#__sr_feedbacks` (`id`, `title`, `reservation_id`, `positive`, `negative`, `like_count`, `dislike_count`, `state`, `created_date`, `modified_date`, `feedback_cache`) VALUES (17, 'Good location', 2, 'Location', 'Small bed', 2, 0, 1, '2015-7-10 08:51:07', '2015-7-10 09:13:39', '{\"attributes\":[{\"feedback_types\":{\"id\":\"11\",\"name\":\"Trip purpose\"},\"feedback_type_values\":[{\"id\":\"19\",\"name\":\"Leisure trip\"}]},{\"feedback_types\":{\"id\":\"12\",\"name\":\"Lengh of stay\"},\"feedback_type_values\":[{\"id\":\"23\",\"name\":\"Stay 2 nights\"}]},{\"feedback_types\":{\"id\":\"13\",\"name\":\"Guest types\"},\"feedback_type_values\":[{\"id\":\"27\",\"name\":\"Family\"}]}],\"scores\":{\"Cleanliness\":\"9\",\"Comfort\":\"8\",\"Location\":\"10\",\"Facilities\":\"8\",\"Staff\":\"9\",\"Value for money\":\"8\",\"Free WiFi\":\"9\"},\"customer\":{\"customer_id\":null,\"reservation_asset_id\":\"8\",\"customer_mobile\":null,\"customer_name\":\"Jacky  Ricky\",\"customer_phone\":\"123456\",\"reservation_asset\":\"Sunflower\",\"customer_country\":\"Italy\",\"customer_country_code\":\"IT\"}}');
INSERT INTO `#__sr_feedbacks` (`id`, `title`, `reservation_id`, `positive`, `negative`, `like_count`, `dislike_count`, `state`, `created_date`, `modified_date`, `feedback_cache`) VALUES (18, 'Elit aut qui sint eius tempora optio eos minus enim', 1, 'Aliquid et et exercitationem temporibus quia et temporibus et veniam, aut dolorem tempora ullamco eligendi nemo perferendis.', 'Ipsa, rerum libero assumenda proident, quae quis odit voluptate est, tempor provident, ea.', 1, 0, 1, '2015-7-10 09:35:24', '0000-0-0 00:00:00', '{\"attributes\":[{\"feedback_types\":{\"id\":\"11\",\"name\":\"Trip purpose\"},\"feedback_type_values\":[{\"id\":\"20\",\"name\":\"Business trip\"}]},{\"feedback_types\":{\"id\":\"12\",\"name\":\"Lengh of stay\"},\"feedback_type_values\":[{\"id\":\"24\",\"name\":\"Stay 3 nights\"}]},{\"feedback_types\":{\"id\":\"13\",\"name\":\"Guest types\"},\"feedback_type_values\":[{\"id\":\"26\",\"name\":\"Couple\"}]}],\"scores\":{\"Cleanliness\":\"2\",\"Comfort\":\"8\",\"Location\":\"2\",\"Facilities\":\"9\",\"Staff\":\"7\",\"Value for money\":\"3\",\"Free WiFi\":\"9\"},\"customer\":{\"customer_id\":null,\"reservation_asset_id\":\"8\",\"customer_mobile\":null,\"customer_name\":\"Billy  Tom\",\"customer_phone\":\"123456\",\"reservation_asset\":\"Sunflower\",\"customer_country\":\"United States\",\"customer_country_code\":\"US\"}}');
INSERT INTO `#__sr_feedbacks` (`id`, `title`, `reservation_id`, `positive`, `negative`, `like_count`, `dislike_count`, `state`, `created_date`, `modified_date`, `feedback_cache`) VALUES (19, 'Better English speaking staff would help', 30, 'I like the location of the hotel as well as the attention given by the staff, although not fluent in English', 'Sluggish wi-fi', 0, 0, 1, '2015-7-10 09:51:59', '0000-0-0 00:00:00', '{\"attributes\":[{\"feedback_types\":{\"id\":\"11\",\"name\":\"Trip purpose\"},\"feedback_type_values\":[{\"id\":\"20\",\"name\":\"Business trip\"}]},{\"feedback_types\":{\"id\":\"12\",\"name\":\"Lengh of stay\"},\"feedback_type_values\":[{\"id\":\"24\",\"name\":\"Stay 3 nights\"}]},{\"feedback_types\":{\"id\":\"13\",\"name\":\"Guest types\"},\"feedback_type_values\":[{\"id\":\"25\",\"name\":\"Group of friends\"}]}],\"scores\":{\"Cleanliness\":\"7\",\"Comfort\":\"9\",\"Location\":\"8\",\"Facilities\":\"9\",\"Staff\":\"9\",\"Value for money\":\"9\",\"Free WiFi\":\"10\"},\"customer\":{\"customer_id\":null,\"reservation_asset_id\":\"8\",\"customer_mobile\":null,\"customer_name\":\"Lemon Fruit Juice\",\"customer_phone\":\"841223456789\",\"reservation_asset\":\"Sunflower\",\"customer_country\":\"Viet Nam\",\"customer_country_code\":\"VN\"}}');
INSERT INTO `#__sr_feedbacks` (`id`, `title`, `reservation_id`, `positive`, `negative`, `like_count`, `dislike_count`, `state`, `created_date`, `modified_date`, `feedback_cache`) VALUES (20, 'Exceptional', 29, 'location is good , hotel clean n good amenties, near underground', 'room a little bit small but acceptable , washroom is good enough though', 0, 0, 1, '2015-7-10 09:52:50', '0000-0-0 00:00:00', '{\"attributes\":[{\"feedback_types\":{\"id\":\"11\",\"name\":\"Trip purpose\"},\"feedback_type_values\":[{\"id\":\"19\",\"name\":\"Leisure trip\"}]},{\"feedback_types\":{\"id\":\"12\",\"name\":\"Lengh of stay\"},\"feedback_type_values\":[{\"id\":\"22\",\"name\":\"Stayed 1 night\"}]},{\"feedback_types\":{\"id\":\"13\",\"name\":\"Guest types\"},\"feedback_type_values\":[{\"id\":\"26\",\"name\":\"Couple\"}]}],\"scores\":{\"Cleanliness\":\"9\",\"Comfort\":\"9\",\"Location\":\"9\",\"Facilities\":\"8\",\"Staff\":\"7\",\"Value for money\":\"9\",\"Free WiFi\":\"10\"},\"customer\":{\"customer_id\":null,\"reservation_asset_id\":\"8\",\"customer_mobile\":null,\"customer_name\":\"Strawberry Fruit Ms\",\"customer_phone\":\"841223456789\",\"reservation_asset\":\"Sunflower\",\"customer_country\":\"Viet Nam\",\"customer_country_code\":\"VN\"}}');
INSERT INTO `#__sr_feedbacks` (`id`, `title`, `reservation_id`, `positive`, `negative`, `like_count`, `dislike_count`, `state`, `created_date`, `modified_date`, `feedback_cache`) VALUES (21, 'very large hotel in a great spot - brand spanking new but rooms tiny', 28, 'rooms really small - in fact the smallest I\'ve stayed in in Tokyo -and I booked a double!\r\nwindows a business to get to as the bed is in the way and they are high set so not much of a panorama from your tiny room', 'friendly staff - very accommodating and happy to go the extra yards ..I was offered a portable wi-fi for the week which made a huge difference and overcame the poor in house wi-fi', 1, 0, 1, '2015-7-10 09:53:43', '0000-0-0 00:00:00', '{\"attributes\":[{\"feedback_types\":{\"id\":\"11\",\"name\":\"Trip purpose\"},\"feedback_type_values\":[{\"id\":\"20\",\"name\":\"Business trip\"}]},{\"feedback_types\":{\"id\":\"12\",\"name\":\"Lengh of stay\"},\"feedback_type_values\":[{\"id\":\"23\",\"name\":\"Stay 2 nights\"}]},{\"feedback_types\":{\"id\":\"13\",\"name\":\"Guest types\"},\"feedback_type_values\":[{\"id\":\"25\",\"name\":\"Group of friends\"}]}],\"scores\":{\"Cleanliness\":\"9\",\"Comfort\":\"8\",\"Location\":\"8\",\"Facilities\":\"9\",\"Staff\":\"7\",\"Value for money\":\"7\",\"Free WiFi\":\"10\"},\"customer\":{\"customer_id\":null,\"reservation_asset_id\":\"8\",\"customer_mobile\":null,\"customer_name\":\"Banana Fruit Mr\",\"customer_phone\":\"841223456789\",\"reservation_asset\":\"Sunflower\",\"customer_country\":\"Viet Nam\",\"customer_country_code\":\"VN\"}}');
INSERT INTO `#__sr_feedbacks` (`id`, `title`, `reservation_id`, `positive`, `negative`, `like_count`, `dislike_count`, `state`, `created_date`, `modified_date`, `feedback_cache`) VALUES (22, 'Every thing was the best', 27, 'Nothing', 'Every thing', 0, 0, 1, '2015-7-10 09:54:35', '0000-0-0 00:00:00', '{\"attributes\":[{\"feedback_types\":{\"id\":\"11\",\"name\":\"Trip purpose\"},\"feedback_type_values\":[{\"id\":\"19\",\"name\":\"Leisure trip\"}]},{\"feedback_types\":{\"id\":\"12\",\"name\":\"Lengh of stay\"},\"feedback_type_values\":[{\"id\":\"23\",\"name\":\"Stay 2 nights\"}]},{\"feedback_types\":{\"id\":\"13\",\"name\":\"Guest types\"},\"feedback_type_values\":[{\"id\":\"27\",\"name\":\"Family\"}]}],\"scores\":{\"Cleanliness\":\"10\",\"Comfort\":\"10\",\"Location\":\"10\",\"Facilities\":\"10\",\"Staff\":\"10\",\"Value for money\":\"10\",\"Free WiFi\":\"10\"},\"customer\":{\"customer_id\":null,\"reservation_asset_id\":\"8\",\"customer_mobile\":null,\"customer_name\":\"Orange juice fruit\",\"customer_phone\":\"841223456789\",\"reservation_asset\":\"Sunflower\",\"customer_country\":\"Viet Nam\",\"customer_country_code\":\"VN\"}}');
INSERT INTO `#__sr_feedbacks` (`id`, `title`, `reservation_id`, `positive`, `negative`, `like_count`, `dislike_count`, `state`, `created_date`, `modified_date`, `feedback_cache`) VALUES (23, 'Good location', 26, 'Staff helpful', 'Quality and speed of wifi', 1, 0, 1, '2015-7-10 09:55:27', '0000-0-0 00:00:00', '{\"attributes\":[{\"feedback_types\":{\"id\":\"11\",\"name\":\"Trip purpose\"},\"feedback_type_values\":[{\"id\":\"20\",\"name\":\"Business trip\"}]},{\"feedback_types\":{\"id\":\"12\",\"name\":\"Lengh of stay\"},\"feedback_type_values\":[{\"id\":\"24\",\"name\":\"Stay 3 nights\"}]},{\"feedback_types\":{\"id\":\"13\",\"name\":\"Guest types\"},\"feedback_type_values\":[{\"id\":\"25\",\"name\":\"Group of friends\"}]}],\"scores\":{\"Cleanliness\":\"9\",\"Comfort\":\"9\",\"Location\":\"9\",\"Facilities\":\"8\",\"Staff\":\"8\",\"Value for money\":\"8\",\"Free WiFi\":\"6\"},\"customer\":{\"customer_id\":null,\"reservation_asset_id\":\"8\",\"customer_mobile\":null,\"customer_name\":\"Pee Little Mr\",\"customer_phone\":\"841223456789\",\"reservation_asset\":\"Sunflower\",\"customer_country\":\"Viet Nam\",\"customer_country_code\":\"VN\"}}');
INSERT INTO `#__sr_feedbacks` (`id`, `title`, `reservation_id`, `positive`, `negative`, `like_count`, `dislike_count`, `state`, `created_date`, `modified_date`, `feedback_cache`) VALUES (24, 'Best location ever', 25, 'The location', 'Pricey and the breakfast was not fantastic', 1, 0, 1, '2015-7-10 09:56:12', '0000-0-0 00:00:00', '{\"attributes\":[{\"feedback_types\":{\"id\":\"11\",\"name\":\"Trip purpose\"},\"feedback_type_values\":[{\"id\":\"19\",\"name\":\"Leisure trip\"}]},{\"feedback_types\":{\"id\":\"12\",\"name\":\"Lengh of stay\"},\"feedback_type_values\":[{\"id\":\"22\",\"name\":\"Stayed 1 night\"}]},{\"feedback_types\":{\"id\":\"13\",\"name\":\"Guest types\"},\"feedback_type_values\":[{\"id\":\"25\",\"name\":\"Group of friends\"}]}],\"scores\":{\"Cleanliness\":\"10\",\"Comfort\":\"10\",\"Location\":\"10\",\"Facilities\":\"10\",\"Staff\":\"10\",\"Value for money\":\"7\",\"Free WiFi\":\"10\"},\"customer\":{\"customer_id\":null,\"reservation_asset_id\":\"8\",\"customer_mobile\":null,\"customer_name\":\"Travel Travel Travel\",\"customer_phone\":\"841223456789\",\"reservation_asset\":\"Sunflower\",\"customer_country\":\"Viet Nam\",\"customer_country_code\":\"VN\"}}');

INSERT INTO `#__sr_feedback_attributes` (`id`, `name`) VALUES (11, 'Trip purpose');
INSERT INTO `#__sr_feedback_attributes` (`id`, `name`) VALUES (12, 'Length of stay');
INSERT INTO `#__sr_feedback_attributes` (`id`, `name`) VALUES (13, 'Guest types');

INSERT INTO `#__sr_feedback_conditions` (`id`, `field`) VALUES (8, 'Cleanliness');
INSERT INTO `#__sr_feedback_conditions` (`id`, `field`) VALUES (9, 'Comfort');
INSERT INTO `#__sr_feedback_conditions` (`id`, `field`) VALUES (10, 'Location');
INSERT INTO `#__sr_feedback_conditions` (`id`, `field`) VALUES (11, 'Facilities');
INSERT INTO `#__sr_feedback_conditions` (`id`, `field`) VALUES (12, 'Staff');
INSERT INTO `#__sr_feedback_conditions` (`id`, `field`) VALUES (13, 'Value for money');
INSERT INTO `#__sr_feedback_conditions` (`id`, `field`) VALUES (14, 'Free WiFi');

INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (15, 17, 9, 8);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (16, 17, 8, 9);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (17, 17, 10, 10);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (18, 17, 8, 11);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (19, 17, 9, 12);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (20, 17, 8, 13);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (21, 17, 9, 14);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (22, 18, 2, 8);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (23, 18, 8, 9);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (24, 18, 2, 10);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (25, 18, 9, 11);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (26, 18, 7, 12);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (27, 18, 3, 13);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (28, 18, 9, 14);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (29, 19, 7, 8);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (30, 19, 9, 9);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (31, 19, 8, 10);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (32, 19, 9, 11);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (33, 19, 9, 12);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (34, 19, 9, 13);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (35, 19, 10, 14);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (36, 20, 9, 8);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (37, 20, 9, 9);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (38, 20, 9, 10);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (39, 20, 8, 11);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (40, 20, 7, 12);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (41, 20, 9, 13);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (42, 20, 10, 14);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (43, 21, 9, 8);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (44, 21, 8, 9);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (45, 21, 8, 10);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (46, 21, 9, 11);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (47, 21, 7, 12);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (48, 21, 7, 13);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (49, 21, 10, 14);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (50, 22, 10, 8);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (51, 22, 10, 9);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (52, 22, 10, 10);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (53, 22, 10, 11);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (54, 22, 10, 12);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (55, 22, 10, 13);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (56, 22, 10, 14);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (57, 23, 9, 8);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (58, 23, 9, 9);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (59, 23, 9, 10);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (60, 23, 8, 11);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (61, 23, 8, 12);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (62, 23, 8, 13);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (63, 23, 6, 14);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (64, 24, 10, 8);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (65, 24, 10, 9);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (66, 24, 10, 10);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (67, 24, 10, 11);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (68, 24, 10, 12);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (69, 24, 7, 13);
INSERT INTO `#__sr_feedback_scores` (`id`, `feedback_id`, `score`, `field_id`) VALUES (70, 24, 10, 14);



INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (19, 'Leisure trip', 11);
INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (20, 'Business trip', 11);
INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (21, 'Honey moon trip', 11);
INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (22, 'Stayed 1 night', 12);
INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (23, 'Stay 2 nights', 12);
INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (24, 'Stay 3 nights', 12);
INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (25, 'Group of friends', 13);
INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (26, 'Couple', 13);
INSERT INTO `#__sr_feedback_attribute_values` (`id`, `name`, `attribute_id`) VALUES (27, 'Family', 13);

INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (107, 17, 19);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (108, 17, 23);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (109, 17, 27);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (110, 18, 20);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (111, 18, 24);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (112, 18, 26);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (113, 19, 20);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (114, 19, 24);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (115, 19, 25);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (116, 20, 19);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (117, 20, 22);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (118, 20, 26);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (119, 21, 20);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (120, 21, 23);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (121, 21, 25);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (122, 22, 19);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (123, 22, 23);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (124, 22, 27);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (125, 23, 20);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (126, 23, 24);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (127, 23, 25);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (128, 24, 19);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (129, 24, 22);
INSERT INTO `#__sr_feedback_attribute_xref` (`id`, `feedback_id`, `feedback_attribute_value_id`) VALUES (130, 24, 25);